function Home() {
    return (
        <>
        {/*Slider Area*/}
		<section class="slider">
			<div class="hero-slider">
				{/*Start Single Slider*/}
				<div class="single-slider" style="background-image:url('img/slider2.jpg')">
					<div class="container">
						<div class="row">
							<div class="col-lg-7">
								<div class="text">
									<h1>Why <span>Electro Homeopathic?</span> </h1>
									<p>Electro Homeopathic Clinic provides safe, natural, and effective homeopathic treatments using advanced electrohomeopathy techniques. </p>
									<div class="button">
										<a href="#" class="btn">Get Appointment</a>
										{/*<a href="#" class="btn primary">Learn More</a>*/}
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				{/*End Single Slider*/}
				{/*Start Single Slider*/}
				
				{/*Start End Slider*/}
				{/*Start Single Slider*/}
				<div class="single-slider" style="background-image:url('img/slider3.jpg')">
					<div class="container">
						<div class="row">
							<div class="col-lg-7">
								<div class="text">
									<h1>How<span> Electro Homeopathy Works!</span></h1>
									<p>Electrohomeopathy is a natural healing method that uses electrical impulses generated by homeopathic remedies to stimulate the body's self-healing processes. It focuses on treating the root cause of illnesses rather than simply alleviating symptoms.

By combining the power of homeopathy with modern electrotherapy, our treatments are precise, painless, and free from side effects.</p>
									<div class="button">
										<a href="#" class="btn">Get Appointment</a>
										<a href="#" class="btn primary">Conatct Now</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				{/*End Single Slider*/}
			</div>
		</section>
		{/*End Slider Area*/}
		
		{/*Start Schedule Area*/}
		<section class="schedule">
			<div class="container">
				<div class="schedule-inner">
					<div class="row">
						<div class="col-lg-4 col-md-6 col-12 ">
							{/*single-schedule*/}
							<div class="single-schedule first">
								<div class="inner">
									<div class="icon">
										<i class="fa fa-ambulance"></i>
									</div>
									<div class="single-content">
										<h4>DR. B.Singh</h4>
										<p> B. Pharma, B.E.M.S.Medicine  <br></br>
										With over 8+ years of experience in homeopathy and electrohomeopathy, Dr. Singh combines compassionate care with scientific expertise to offer personalized treatment plans tailored to each patient's unique needs.<br></br>
										</p>
										{/*<a href="#">LEARN MORE<i class="fa fa-long-arrow-right"></i></a>*/}
									</div>
								</div>
							</div>
						</div>
						
						<div class="col-lg-4 col-md-12 col-12">
							{/*single-schedule*/}
							<div class="single-schedule last">
								<div class="inner">
									<div class="icon">
										<i class="icofont-ui-clock"></i>
									</div>
									<div class="single-content">
										<h4>Opening Hours</h4>
										<ul class="time-sidual">
											<li class="day">Monday - Friday <span>10 AM- 11 PM</span></li>
											<li class="day">Saturday <span>9.00-10.30</span></li>
											{/*<li class="day">Monday - Thusday <span>9.00-15.00</span></li>*/}
										</ul>
										<a href="#">LEARN MORE<i class="fa fa-long-arrow-right"></i></a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		{/*End Start schedule Area*/}

		{/*Start Feautes*/}
		<section class="Feautes section">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="section-title">
							<h2>We Are Always Ready to Help You & Your Family</h2>
							<img src="img/section-img.png" alt="#" />
							<p>Lorem ipsum dolor sit amet consectetur adipiscing elit praesent aliquet. pretiumts</p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-4 col-12">
						{/*Start Single features*/}
						<div class="single-features">
							<div class="signle-icon">
								<i class="icofont icofont-ambulance-cross"></i>
							</div>
							<h3>Pain Management</h3>
							<p>Utilizing electro-stimulation for relief from chronic and acute pain conditions, encouraging tissue repair and nerve function.</p>
						</div>
						{/*End Single features*/}
					</div>
					<div class="col-lg-4 col-12">
						{/*Start Single features*/}
						<div class="single-features">
							<div class="signle-icon">
								<i class="icofont icofont-medical-sign-alt"></i>
							</div>
							<h3>Immune Support</h3>
							<p>Strengthens the immune system through subtle energy modulation to help prevent illness and improve overall wellness.</p>
						</div>
						{/*End Single features*/}
					</div>
					<div class="col-lg-4 col-12">
						{/*Start Single features*/}
						<div class="single-features last">
							<div class="signle-icon">
								<i class="icofont icofont-stethoscope"></i>
							</div>
							<h3>Digestive Health</h3>
							<p>Promotes digestive system balance, assisting in relieving discomfort and improving nutrient absorption naturally.</p>
						</div>
						{/*End Single features*/}
					</div>
				</div>
			</div>
		</section>
		{/*End Feautes -->
		
		<!-- Start Fun-facts -->
	
		<!--/ End Fun-facts -->
		
		<!-- Start Why choose -->
		<!-- <section class="why-choose section" >
			
		</section>
		<!--/ End Why choose -->
		
		<!-- Start Call to action -->
		<!-- <section class="call-action overlay" data-stellar-background-ratio="0.5">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-12">
						<div class="content">
							<h2>Do you need Emergency Medical Care? Call @ 1234 56789</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque porttitor dictum turpis nec gravida.</p>
							<div class="button">
								<a href="#" class="btn">Contact Now</a>
								<a href="#" class="btn second">Learn More<i class="fa fa-long-arrow-right"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section> -->
		<!--/ End Call to action -->
		
		<!-- Start portfolio -->
	
		<!--/ End portfolio -->
		
		<!-- Start service -->
		
		<!--/ End service -->
		
		<!-- Pricing Table -->
		
		<!--/ End Pricing Table -->
		
		
		
		<!-- Start Blog Area -->
		
		<!-- End Blog Area -->
		
		<!-- Start clients -->
		
		<!--/Ens clients -->
		
	
		<!-- End Appointment -->
		
	
		<!-- /End Newsletter Area --> */}
        </>
    )
}